el1 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.RelativeLayout/android.widget.TextView[2]")
el1.click()
el2 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.TextView[2]")
el2.click()
el3 = driver.find_element_by_id("com.felink.videopaper.mi:id/dialog_submit")
el3.click()
el4 = driver.find_element_by_id("com.felink.videopaper.mi:id/tv_make")
el4.click()
el5 = driver.find_element_by_id("com.felink.videopaper.mi:id/img_select_material")
el5.click()
el6 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/android.support.v7.widget.RecyclerView/android.widget.RelativeLayout[3]/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.ImageView")
el6.click()
el7 = driver.find_element_by_id("com.felink.videopaper.mi:id/tv_rightBtn")
el7.click()
el8 = driver.find_element_by_id("com.felink.videopaper.mi:id/crop_finish_btn")
el8.click()
el9 = driver.find_element_by_id("com.felink.videopaper.mi:id/btn_next")
el9.click()
el10 = driver.find_element_by_id("com.felink.videopaper.mi:id/tv_make")
el10.click()
el11 = driver.find_element_by_id("com.felink.videopaper.mi:id/img_home")
el11.click()
